from datetime import datetime, timezone
from decimal import Decimal
from uuid import UUID, uuid4
from sqlalchemy import String, DateTime, Float, ForeignKey, Numeric, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column
from app.db.base import Base
class Signal(Base):
    """Trading signal generated by strategy"""
    __tablename__ = "signals"
    id: Mapped[UUID] = mapped_column(primary_key=True, default=uuid4)
    strategy_id: Mapped[UUID] = mapped_column(ForeignKey("strategies.id", ondelete="CASCADE"), nullable=False)
    symbol_id: Mapped[UUID] = mapped_column(ForeignKey("symbols.id", ondelete="CASCADE"), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
        nullable=False,
    )
    signal_time: Mapped[datetime] = mapped_column(DateTime(timezone=True), index=True, nullable=False)
    session_name: Mapped[str | None] = mapped_column(String(20), nullable=True)
    direction: Mapped[str] = mapped_column(String(10), nullable=False)
    status: Mapped[str] = mapped_column(String(20), default="active", index=True, nullable=False)
    priority_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    confidence_band: Mapped[str | None] = mapped_column(String(10), nullable=True)
    htf_bias: Mapped[str | None] = mapped_column(String(10), nullable=True)
    entry_tf: Mapped[str | None] = mapped_column(String(10), nullable=True)
    entry_zone_low: Mapped[Decimal | None] = mapped_column(Numeric(12, 5), nullable=True)
    entry_zone_high: Mapped[Decimal | None] = mapped_column(Numeric(12, 5), nullable=True)
    stop_price: Mapped[Decimal | None] = mapped_column(Numeric(12, 5), nullable=True)
    target_1: Mapped[Decimal | None] = mapped_column(Numeric(12, 5), nullable=True)
    target_2: Mapped[Decimal | None] = mapped_column(Numeric(12, 5), nullable=True)
    expiry_time: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    reason_code: Mapped[str | None] = mapped_column(String(50), nullable=True)
    reason_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    json_context: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
